name: Docker-Image 

on:
  workflow_dispatch
  

jobs:
  

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14          
      - run: npm ci
  
  linter:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-image:

    runs-on: ubuntu-20.04
    needs: [linter]
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t annaneilan/devops-node-app .
      
  push-image:
      runs-on: ubuntu-20.04
      needs: [build-image]

      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: ${{secrets.DOCKERHUB_REPO}}:latest
